all : ex00 ex01 ex02


ex00:
	@make -C ./ex00

ex01:
	@make -C ./ex01

ex02:
	@make -C ./ex02

clean:
	@make -C ./ex00 clean
	@make -C ./ex01 clean
	@make -C ./ex02 clean

.PHONY: clean ex00 ex01 ex02
